services:
  - type: web
    name: silent-strings
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 app:app"
    envVars:
      - key: GOOGLE_CLIENT_ID
        value: 949946644536-nff8bkcubtnnvhehar80q1trpkbdmvvs.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: FLASK_SECRET_KEY
        value: silent-string-key-game
