"""add_mfa_and_privacy_fields

Revision ID: 6ef971e77778
Revises: 3d67476d6873
Create Date: 2025-06-22 15:33:49.856932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef971e77778'
down_revision: Union[str, None] = '3d67476d6873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('profile_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_public')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
