"""Add avatar fields

Revision ID: 86b595641d6d
Revises: 8137104cbfd2
Create Date: 2025-06-01 16:59:49.852213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b595641d6d'
down_revision: Union[str, None] = '8137104cbfd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_face', sa.String(length=120), nullable=True))
    op.drop_column('users', 'avatar_eyes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_eyes', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_face')
    # ### end Alembic commands ###
