"""Add achievements and unlocks to user

Revision ID: bfc5aea5d7b6
Revises: 4b3747c1ce99
Create Date: 2025-06-09 12:08:17.968436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfc5aea5d7b6'
down_revision: Union[str, None] = '4b3747c1ce99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('achievements', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('unlocks', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unlocks')
    op.drop_column('users', 'achievements')
    # ### end Alembic commands ###
