"""Add avatar columns to users table

Revision ID: f3ba55470427
Revises: 4e6c7b758352
Create Date: 2025-05-30 21:54:50.125511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ba55470427'
down_revision: Union[str, None] = '4e6c7b758352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_character', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('avatar_hair', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('avatar_clothes', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('avatar_acc', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('avatar_eyes', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_eyes')
    op.drop_column('users', 'avatar_acc')
    op.drop_column('users', 'avatar_clothes')
    op.drop_column('users', 'avatar_hair')
    op.drop_column('users', 'avatar_character')
    # ### end Alembic commands ###
